### ISSUE TITLE
-o Option has no effect

### ISSUE THREAD

**Issue by JayWalker512** [darakian/ddh#13]
I built ddh from master branch on Ubuntu 16.04 with rustc 1.33.0-nightly (ec194646f 2019-01-02). Used 'cargo build --release' to compile.

If I run ddh from the target/release directory with the following command in the target/release directory: 
```
./ddh ~/Downloads/ -f json -o ~/Downloads/dupes.json
```
The dupes.json file is created in the current working directory (target/release) but not at the location specified (~/Downloads/dupes.json). 

Despite this minor issue, I really appreciate this tool! Thank you for your hard work :+1:

**Comment by darakian** [comment]
Glad you like it. Looks like I'm doing a split on the right most `/` and taking the value after that as the output file. Code is
```
let out_file = _string.rsplit("/").next().unwrap_or("Results.txt");
```

Give me some time to figure out why I did this and to rewrite that block. Odds are this was a short cut for proper path checking. I'll have a commit for you in the next day or two :)

**Comment by darakian** [comment]
@JayWalker512 One more commit in. Can you give it a spin?

**Comment by JayWalker512** [comment]
That fixed the issue of the output file not being created in the specified directory! Though there's a new issue where ddh asks me if I wish to overwrite the output file even if it hadn't previously existed. Eg:

```
rm ~/Downloads/dupes.json
./ddh ~/Downloads/ -f json -o ~/Downloads/dupes.json
5792 Total files (with duplicates): 7967 Megabytes
5436 Total files (without duplicates): 7947 Megabytes
5355 Single instance files: 7928 Megabytes
81 Shared instance files: 19 Megabytes (437 instances)
---
File /home/jaywalker/Downloads/dupes.json already exists.
Overwrite? Y/N
```

Your discretion if this should be a separate issue, probably just a mistaken order in which you check for the file existing and creating it.

**Comment by darakian** [comment]
Just me trying to keep this to a one line fix and failing. Once more?

**Comment by JayWalker512** [comment]
We have a winner! Seems to be working correctly now :+1:

**Comment by darakian** [comment]
Right on. Open another issue if you run into troubles and thanks for the testing btw :)
