### ISSUE TITLE
benchmarking and comparison with similar tools

### ISSUE THREAD

**Issue by matu3ba** [darakian/ddh#22]

**Comment by darakian** [comment]
Can you elaborate on what you're looking for?

**Comment by matu3ba** [comment]
The 4 most known duplication finders [are](https://www.tecmint.com/find-and-delete-duplicate-files-in-linux/) `rdfind`,`fdupes`,`dupeGuru`,`FSlint`.  
You could benchmark and compare against them.

**Comment by darakian** [comment]
I could. I probably wont, but certainly I could :)

**Comment by neunmalelf** [comment]
2021-12-04

local directory with 930 jpeg files with 2 duplicate jpeg files

ubuntu 20.04 no GUI :
```
rdfind   real: 0m00.657s   user: 0m00.007s  sys: 0m00.114s
ddh      real: 0m00.007s   user: 0m00.002s  sys: 0m00.004s
fdupes   real: 0m32.932s   user: 0m00.074s  sys: 0m05.685s
```

Windows 11 pro:
```
ddh        total: 0m00.011s (started from a .cmd file) 
powershell total: 0m00.012s (incl. grouping & sorting)
DupeGuru coulnd't the duplicate files
```

Overall i would say **nice job** 👍👏.

PS: Some of the rdfind options would be nice (shameless I know 😇)
