### ISSUE TITLE
error: "thread '<unknown>' has overflowed its stack"

### ISSUE THREAD

**Issue by fiveseven808** [darakian/ddh#3]
Steps to reproduce:
Compile with `cargo build`
Run `setx RUST_BACKTRACE 1`
Open new shell (variable does set in current shell)
Run `ddh c:\users\myuser`

Output: `thread '<unknown>' has overflowed its stack`

**Comment by darakian** [comment]
Note: Note windows specific

**Comment by fiveseven808** [comment]
After compiling and running the latest version, I still encounter the same error when running it against my user directory.

**Comment by darakian** [comment]
Fixed in a6173a516f38a64059eb7f03a26d013500bd3ceb
