### ISSUE TITLE
ddh not working with directories have Arabic characters

### ISSUE THREAD

**Issue by moaz-mokhtar** [darakian/ddh#30]
Hello

First thank you for the idea and this implementation.

I tested that in a folder which contains Arabic word but doesn't affected.
I learning rust and I'm interested to participate to fix like these issues but may need some hint if possible.
![issue](https://user-images.githubusercontent.com/5870208/87244094-68e25780-c43b-11ea-9019-9622f1e3d736.PNG)

**Comment by darakian** [comment]
Thanks for the bug report. Can you test if the issue is only for directories or do files with arabic characters also fail to get processed?

**Comment by darakian** [comment]
Quick test on my end show that ddh is entering a dir and can read the contents within
```
jon~/D/g/!/ddh:ma.get/debug/ddh  أَلْحُرُوف -o noo no
Processing "أ\u{64e}ل\u{652}ح\u{64f}ر\u{64f}وف"
Current metadata Metadata { file_type: FileType(FileType { mode: 16877 }), is_dir: true, is_file: false, permissions: Permissions(FilePermissions { mode: 16877 }), modified: Ok(SystemTime { tv_sec: 1594578524, tv_nsec: 182247154 }), accessed: Ok(SystemTime { tv_sec: 1594578526, tv_nsec: 815872904 }), created: Ok(SystemTime { tv_sec: 1594578346, tv_nsec: 696352429 }) }
1 Total files (with duplicates): 0 Megabytes
1 Total files (without duplicates): 0 Megabytes
1 Single instance files: 0 Megabytes
0 Shared instance files: 0 Megabytes (0 instances)
```

and the tree
```
jon~/D/g/!/ddh:master❯❯❯ tree أَلْحُرُوف/
أ�\216�\204�\222ح�\217ر�\217�\210�\201/
└── foo.txt

0 directories, 1 file
```

**Comment by moaz-mokhtar** [comment]
Very thankful for your feedback.

I created a Folder with some different languages (Arabic, Chinese, and Malayalam) as below:

   ![CMD - Testing lang support content](https://user-images.githubusercontent.com/5870208/87313965-ea60e500-c522-11ea-9228-74f6e3480b69.PNG)

   ![Testing lang support content](https://user-images.githubusercontent.com/5870208/87313662-7e7e7c80-c522-11ea-8aa2-703d2d3701b0.PNG)

===========

While I'm testing through CMD , Powershell, and Windows Terminal I found different behaviors, so I preferred to make a table which contains more details.
Note that I mean Singletons is the last row in the Results.txt which contains information about the search Folder which I noticed it is not appearing in most cases.

Terminal name | Folder tested | ddh call location | Shows Results ? | Terminal results | Singletons in Results ?
-- | -- | -- | -- | -- | --
CMD - standalone | D:\Knowledge - العلوم | Inside test folder | Yes | d:\Knowledge - العلوم>ddh .     2831 Total files (with duplicates): 21267 Megabytes     2473 Total files (without duplicates): 20985 Megabytes     2252 Single instance files: 20718 Megabytes     221 Shared instance files: 267 Megabytes (579 instances)     Standard results written to Results.txt | No
CMD - standalone | D:\Testing lang support | Inside test folder | Yes | d:\Testing lang support>ddh .     14 Total files (with duplicates): 0 Megabytes     4 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     4 Shared instance files: 0 Megabytes (14 instances)     Standard results written to Results.txt | No
CMD - Win Terminal | D:\Knowledge - العلوم | Outside test folder | Yes | C:\Users>ddh "D:\Knowledge -   العلوم"     2832 Total files (with duplicates): 21267 Megabytes     2474 Total files (without duplicates): 20986 Megabytes     2253 Single instance files: 20718 Megabytes     221 Shared instance files: 267 Megabytes (579 instances)     Standard results written to Results.txt | No
CMD - Win Terminal | D:\Testing lang support | Outside test folder | Yes | C:\Users>ddh "D:\Testing lang   support"     15 Total files (with duplicates): 0 Megabytes     5 Total files (without duplicates): 0 Megabytes     1 Single instance files: 0 Megabytes     4 Shared instance files: 0 Megabytes (14 instances)     Standard results written to Results.txt | Yes
CMD - Win Terminal | D:\Knowledge - العلوم | Inside test folder | Yes | D:\Knowledge - العلوم>ddh .     2831 Total files (with duplicates): 21267 Megabytes     2473 Total files (without duplicates): 20985 Megabytes     2252 Single instance files: 20718 Megabytes     221 Shared instance files: 267 Megabytes (579 instances)     Standard results written to Results.txt | No
CMD - Win Terminal | D:\Testing lang support | Inside test folder | Yes | D:\Testing lang support>ddh .     14 Total files (with duplicates): 0 Megabytes     4 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     4 Shared instance files: 0 Megabytes (14 instances)     Standard results written to Results.txt | No
Powershell - standalone | D:\Knowledge - العلوم | Outside test folder | No | PS D:\> ddh 'D:\Knowledge - العلوم\'     0 Total files (with duplicates): 0 Megabytes     0 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     0 Shared instance files: 0 Megabytes (0 instances)     Standard results written to Results.txt | No
Powershell - standalone | D:\Testing lang support | Outside test folder | No | PS D:\> ddh 'D:\Testing lang support\     0 Total files (with duplicates): 0 Megabytes     0 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     0 Shared instance files: 0 Megabytes (0 instances)     Standard results written to Results.txt | No
Powershell - standalone | D:\Knowledge - العلوم | Inside test folder | Yes | PS D:\Knowledge - العلوم> ddh .     2831 Total files (with duplicates): 21267 Megabytes     2473 Total files (without duplicates): 20985 Megabytes     2252 Single instance files: 20718 Megabytes     221 Shared instance files: 267 Megabytes (579 instances)     Standard results written to Results.txt | No
Powershell - standalone | D:\Testing lang support | Inside test folder | Yes | PS D:\Testing lang support> ddh .     14 Total files (with duplicates): 0 Megabytes     4 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     4 Shared instance files: 0 Megabytes (14 instances)     Standard results written to Results.txt | No
Powershell - Win Terminal | D:\Knowledge - العلوم | Outside test folder | No | PS D:\> ddh '.\Knowledge - العلوم\'     0 Total files (with duplicates): 0 Megabytes     0 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     0 Shared instance files: 0 Megabytes (0 instances)     Standard results written to Results.txt | No
Powershell - Win Terminal | D:\Testing lang support | Outside test folder | No | PS D:\> ddh '.\Testing lang support\'     0 Total files (with duplicates): 0 Megabytes     0 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     0 Shared instance files: 0 Megabytes (0 instances)     Standard results written to Results.txt | No
Powershell - Win Terminal | D:\Knowledge - العلوم | Inside test folder | Yes | PS D:\Knowledge - العلوم> ddh .     2831 Total files (with duplicates): 21267 Megabytes     2473 Total files (without duplicates): 20985 Megabytes     2252 Single instance files: 20718 Megabytes     221 Shared instance files: 267 Megabytes (579 instances)     Standard results written to Results.txt | No
Powershell   - Win Terminal | D:\Testing lang support | Inside test folder | Yes | PS D:\Testing lang support> ddh .     14 Total files (with duplicates): 0 Megabytes     4 Total files (without duplicates): 0 Megabytes     0 Single instance files: 0 Megabytes     4 Shared instance files: 0 Megabytes (14 instances)     Standard results written to Results.txt | No

**Comment by darakian** [comment]
Interesting. I wonder if this is maybe a windows cmd issue? For the singletons issue which seems to affect all cases; can you post some example output?

**Comment by moaz-mokhtar** [comment]
Singletons appeared in one case only:


Terminal name | Folder tested | ddh call location | Shows Results ? | Terminal results | Singletons in Results ?
-- | -- | -- | -- | -- | --
CMD - Win Terminal | D:\Testing lang support | Outside test folder | Yes | C:\Users>ddh "D:\Testing lang   support"     15 Total files (with  duplicates): 0 Megabytes     5 Total files (without duplicates): 0  Megabytes     1 Single instance files: 0 Megabytes     4 Shared instance  files: 0 Megabytes (14 instances)     Standard results written to  Results.txt | Yes

For the print screens, see below:
Below is in the original folder - Knowledge Folder in Arabic
    ![no singletons - Knowledge folder in arabic](https://user-images.githubusercontent.com/5870208/87563420-7a3b9600-c6bf-11ea-9c6f-9702a9d98981.PNG)


Below is in the testing folder - Testing Lang Folder in Arabic
    ![no singletons - Testing Lang folder in arabic](https://user-images.githubusercontent.com/5870208/87563444-8162a400-c6bf-11ea-8a4d-c05cdb2d7c5b.PNG)

**Comment by moaz-mokhtar** [comment]
@darakian 
For the results issue as prev table I found the problem.
Check below screenshot:
     ![error for last slash](https://user-images.githubusercontent.com/5870208/87736937-d7c40580-c7d9-11ea-84c5-7f79bbcf709d.PNG)


So that means user shouldn't add last slash '/' in case he call 'ddh' command form outside the target folder.

**Comment by darakian** [comment]
That's quite bizarre. If anything I would expect that error in the reverse direction where no slash would result in no files found. I've tried to recreate the issue on my end without success.

```
jon~/D/g/!/ddh:master❯❯❯ ./target/debug/ddh lang-test/ -o no
3 Total files (with duplicates): 0 Megabytes
2 Total files (without duplicates): 0 Megabytes
1 Single instance files: 0 Megabytes
1 Shared instance files: 0 Megabytes (2 instances)
jon~/D/g/!/ddh:master❯❯❯ ./target/debug/ddh lang-test -o no
3 Total files (with duplicates): 0 Megabytes
2 Total files (without duplicates): 0 Megabytes
1 Single instance files: 0 Megabytes
1 Shared instance files: 0 Megabytes (2 instances)
jon~/D/g/!/ddh:master❯❯❯ tree lang-test/
lang-test/
├── arabic\ -\ ع�\216ر�\216ب�\220�\212�\221
│   └── foo.txt
├── chinese\ -\ 漢�\236
│   └── foo.txt
└── malay\ -\ ب�\207اس\ �\205�\204ا�\212�\210
    └── foo.txt

3 directories, 3 files
```

If I made a debug branch for you would you be willing to compile and run it to test?

**Comment by moaz-mokhtar** [comment]
Yes of course.

Actually it is good time to till you below:
- I have simple features to improve this tool and empowering my Rust exp. 
- I'm intended to discuss with you to enhance this tool, and I did collect top features for Duplicate Files apps features.
- I did start and implement simple but powerful feature which is the naming of the results file.

========
So do it.. . I'm ready.

**Comment by darakian** [comment]
Awesome. I've made the branch `debug-win-lang-issue`. Could you run it on your language test dir both with and without the `/` and post the results of each?

**Comment by moaz-mokhtar** [comment]
I did test the branch debug-win-lang-issue and found below:

First: 2 code bugs fixed as mentioned. Also it failed as below error which slash '/' included in last directory:
![error in building branch 'debug-win-lang-issue'](https://user-images.githubusercontent.com/5870208/87882581-2dc6c200-ca01-11ea-9c6b-1433ac2f5f56.PNG)

Second: same issue which succeeded without last slash '/'.
![succeded one](https://user-images.githubusercontent.com/5870208/87882594-518a0800-ca01-11ea-9ce8-14e5c4e8b64a.PNG)

**Comment by darakian** [comment]
Oh man sorry about the bugs. Pushed a commit with those fixes. Can you post the output with the slash?

**Comment by darakian** [comment]
One more commit to test with. Can you rerun?

**Comment by moaz-mokhtar** [comment]
Don't be sorry... No worries.....

I did commit. 

But you said:
> 
> 
> One more commit to test with. Can you rerun?
Is my current commit meets your comment?

**Comment by darakian** [comment]
A reset to my commits would be preferred .

**Comment by moaz-mokhtar** [comment]
Do u mean

`git reset - - hard`

**Comment by darakian** [comment]
Ya. Doing a `git reset --hard origin/debug-win-lang-issue` then a `git pull` should ensure that you're on the latest commits. You should see the following commits when you do a git log after the reset and pull.
```
jon~/D/g/!/ddh:debug-win-lang-issue❯❯❯ git log
commit b0fc864bbf90094be3b174d239104fcd0e9ff960 (HEAD -> debug-win-lang-issue, origin/debug-win-lang-issue)
Author: Jon Moroney <darakian@gmail.com>
Date:   Sun Jul 19 12:20:11 2020 -0700

    Cleaner canonicalize

commit 426334ca6960f6bc6cfd40ae0a05a75ef904e996
Author: Jon Moroney <darakian@gmail.com>
Date:   Sun Jul 19 11:57:55 2020 -0700

    canonicalize and back

commit d8c36359064bb449746671602e2697fde5e3dbf2
Author: Jon Moroney <darakian@gmail.com>
Date:   Sun Jul 19 11:53:01 2020 -0700

    fixup! Add simple debug output

commit 024e4946ea15681953868341d299c548acd1d715
Author: Jon Moroney <darakian@gmail.com>
Date:   Sun Jul 19 10:31:42 2020 -0700

    Add simple debug output
```

**Comment by moaz-mokhtar** [comment]
I did as you requested as your advised and below results appeared and I'm worry about a statement which said:

> CONFLICT (content): Merge conflict in src/lib.rs
> Automatic merge failed; fix conflicts and then commit the result.

So what is your opinion?

```
C:\Users\Administrator\dev\repos_rust\ddh-main>git reset --hard origin/debug-win-lang-issue
HEAD is now at 024e494 Add simple debug output

C:\Users\Administrator\dev\repos_rust\ddh-main>git pull
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 59 (delta 34), reused 43 (delta 23), pack-reused 0
Unpacking objects: 100% (59/59), 11.62 KiB | 1024 bytes/s, done.
From https://github.com/darakian/ddh
 + 024e494...5ebc1a0 debug-win-lang-issue -> origin/debug-win-lang-issue  (forced update)
 * [new branch]      factor-out-fileinfo  -> origin/factor-out-fileinfo
 * [new branch]      impl-serialize-for-FileInfo -> origin/impl-serialize-for-FileInfo
   4e7c67c..26e645d  master               -> origin/master
 * [new branch]      skip-hash-unwrap     -> origin/skip-hash-unwrap
 * [new branch]      switch-clap-to-pico-args -> origin/switch-clap-to-pico-args
 * [new branch]      update-dependencies  -> origin/update-dependencies
Auto-merging src/lib.rs
CONFLICT (content): Merge conflict in src/lib.rs
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by darakian** [comment]
Hmmm ok. Well two approaches come to mind. 
1. Delete your local branch and re-checkout mine
`git checkout master; git branch -D debug-win-lang-issue; git checkout debug-win-lang-issue`
2. Just check out the origin branch 
`git checkout origin/debug-win-lang-issue`

2 will put you in a detached head state, but I don't think that will cause issues.

**Comment by moaz-mokhtar** [comment]
Very thankful.
 I did it and did one test and issues.

I will do more tests and will provide a feedback to you.


Note: I did send u email. Kindly check.

**Comment by darakian** [comment]
Any update @moaz-mokhtar ?

**Comment by moaz-mokhtar** [comment]
Hello @darakian 

Apologize for being late.

I did a sample test and found that now in version 0.11.2 results is not correct.
**Inside folder**
![image](https://user-images.githubusercontent.com/5870208/90307689-e8e75b80-ded8-11ea-9c12-af0268cb93b2.png)


***In comparison with old version:***
![image](https://user-images.githubusercontent.com/5870208/90307679-d53bf500-ded8-11ea-93bd-026596205f13.png)


![error - wrong results - 2020-08-15 - ver 0 11 2](https://user-images.githubusercontent.com/5870208/90307602-023bd800-ded8-11ea-9cfa-a74b97134752.png)

**Outside folder**
![image](https://user-images.githubusercontent.com/5870208/90307651-99089480-ded8-11ea-9977-c988378dd68f.png)

**Comment by darakian** [comment]
> Apologize for being late.

No worries. 👍 

> I did a sample test and found that now in version 0.11.2 results is not correct.

That makes sense actually. I didn't add this potential fix to 0.11.2 so it will be have the same behavior with respect to system paths. I can make a new release with a potential fix in it if that's easier for you to test.

**Comment by moaz-mokhtar** [comment]
Good

**Comment by darakian** [comment]
Cool. I'll add it to the next release. I want to add a few more things so give a week or two.

**Comment by moaz-mokhtar** [comment]
no worries take your time.
In case I want to add little features, should I create a branch or pull a request?

**Comment by darakian** [comment]
Pull requests are fine if you intend to code it yourself otherwise use issues to discuss the feature first. There are some features I don't want to add to ddh as well such as modifying duplicates.

**Comment by moaz-mokhtar** [comment]
`There are some features I don't want to add to ddh as well such as modifying duplicates.`

_Man...! we want to develop powerful features and get some benefits or money.... Hahahaha._ 

Anyways.. I respect this, and agree with u to discuss in issues first. This is good option.

**Comment by darakian** [comment]
> Man...! we want to develop powerful features and get some benefits or money.... Hahahaha.

DDH is available in library form as well :)
https://docs.rs/ddh
Though I do need to be better about documenting it.

> Anyways.. I respect this, and agree with u to discuss in issues first. This is good option.

Sounds good.

**Comment by darakian** [comment]
@moaz-mokhtar I've pushed 0.11.3 which includes https://github.com/darakian/ddh/pull/42 and I think that may resolve your issue. Please let me know :)

**Comment by moaz-mokhtar** [comment]
Noted

**Comment by moaz-mokhtar** [comment]
Very thankful.

Now it is resolved but simple issue as below highlighted which it is always string \\\\?\ appeared before the path:

![print error - 2020-08-29](https://user-images.githubusercontent.com/5870208/91636516-8bd3c580-ea01-11ea-9277-9ed191fa8d23.PNG)

**Comment by darakian** [comment]
Awesome. Glad that solved your problem :)
If the `\\?\` is an issue would you mind making a new issue for that? It looks like that's part of the windows extended path syntax
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
and I don't know a clean way to remove that.
