### ISSUE TITLE
Does not handle directories with spaces [windows]

### ISSUE THREAD

**Issue by fiveseven808** [darakian/ddh#4]
Steps to reproduce:
Open a prompt with administrative (or current user) access
Navigate to build directory
Run `.\ddh "c:\users\myuser\desktop"`
Output:

> 0 Total files (with duplicates): 0 Kilobytes
> 0 Total files (without duplicates): 0 Kilobytes
> 0 Single instance files: 0 Kilobytes
> 0 Shared instance files: 0 Kilobytes (0 instances)

However, the program is not completely broken, as if I run a `.\ddh .\`
The output is:

> 168 Total files (with duplicates): 41476 Kilobytes
> 164 Total files (without duplicates): 30693 Kilobytes
> 160 Single instance files: 19911 Kilobytes
> 4 Shared instance files: 10782 Kilobytes (8 instances)

**Comment by fiveseven808** [comment]
Clarification:
It seems to work in some directories, but not others. For instance, I have a c:\intel directory for whatever reason with 3 files in it. ddh runs properly on them.

However, it does not seem to be able to scan any of my user directory folders. e.g. c:\users\myuser\desktop or c:\users\myuser\downloads

Similarly, I cannot run ddh on the directory "C:\Program Files\Git"

This leads me to believe that ddh may not handle paths with spaces in their names properly.

**Comment by fiveseven808** [comment]
Latest version fixes this! I am now able to run ddh against my users folder.

**Comment by darakian** [comment]
Fixed in 4f6dfdfaa034029dd09a1a181f3b857a6feaaee6
