### ISSUE TITLE
Incorrect help output

### ISSUE THREAD

**Issue by Tobi823** [darakian/ddh#47]
`ddh --help` reports:

```
USAGE:
    ddh [OPTIONS] <Directories>...
```

but it should be `ddh <Directories>... [OPTIONS]`.

Sadly I don't know clap and how to fix it.

**Comment by darakian** [comment]
Thanks for the bug report. That's definitely an issue, but I'm not sure what I can do aside from making all inputs position independent which then changes the cli usage. That would require the use of `-d`/`--directories` and that will interfere with anyone's scripting.

That said, I do plan to change the cli interface at some point and I would appreciate any input :)

**Comment by Tobi823** [comment]
I have expressed myself ambiguously - the CLI works fine and it should not be changed. But the documentation (`ddh --help`) is wrong:

According to the documentation, I can do this: `ddh -o no Downloads/`. But this doesn't work:
```
error: The following required arguments were not provided:
    <Directories>...

USAGE:
    ddh <Directories>... --output <Output>

For more information try --help
```

I have to swap `-o no` and `Downloads/`. `ddh Downloads/ -o no` returns the correct output:
```
152 Total files (with duplicates): 94 Megabytes
141 Total files (without duplicates): 90 Megabytes
134 Single instance files: 86 Megabytes
7 Shared instance files: 3 Megabytes (18 instances)
```

This is no problem for experienced developers but maybe for beginners.

**Comment by Tobi823** [comment]
![Screenshot_20201031_141452](https://user-images.githubusercontent.com/10066140/97780217-9f2b1a80-1b83-11eb-86d6-c05870849e90.png)

**Comment by darakian** [comment]
I understand the issue and you're right that is a bug. However the issue stems from my args declarations
```
.arg(Arg::with_name("directories")
...
                               .index(1))
                        .arg(Arg::with_name("Blocksize")
...
```
Short of changing my CLI interface I'm not sure there's anything I can do to fix this.

**Comment by Tobi823** [comment]
I'm closing this issue because:
 - I don't have to time to look deeper into "clap" to fix it (but maybe later?)
 - this bug is not critical, just a little bit annoying

**Comment by Tobi823** [comment]
Beside this little annoyance - the tools works and is very helpful. Thanks :+1:
