### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by fiveseven808** [darakian/ddh#5]
I may have to dig deeper into this issue, however, upon running multiple ddh commands against my desktop, I receive different result. I do not believe any files are change on my desktop. 

1st run:

> 2112 Total files (with duplicates): 586116 Kilobytes
> 2030 Total files (without duplicates): 548212 Kilobytes
> 1983 Single instance files: 523078 Kilobytes
> 47 Shared instance files: 25133 Kilobytes (129 instances)

2nd run:

> 2112 Total files (with duplicates): 586116 Kilobytes
> 2031 Total files (without duplicates): 549007 Kilobytes
> 1984 Single instance files: 523873 Kilobytes
> 47 Shared instance files: 25133 Kilobytes (128 instances)

3rd run:

> 2112 Total files (with duplicates): 586116 Kilobytes
> 2030 Total files (without duplicates): 548192 Kilobytes
> 1982 Single instance files: 522243 Kilobytes
> 48 Shared instance files: 25948 Kilobytes (130 instances)

**Comment by darakian** [comment]
First thing to try is save a csv output to a file a few times and check the diff of these files. Please check and report back.

**Comment by darakian** [comment]
This may have been related to how symlinks were handled in a prior version. This should be fixed in the current version.
