### ISSUE TITLE
Updated Windows release?

### ISSUE THREAD

**Issue by arimgibson** [darakian/ddh#50]
Thanks for this software, has been a game changer coming from a robust but awfully slow (Python) duplicate checker with a much less sophistocated algorithm. 

Would you be able to compile a new Windows release (and for that matter, Linux and MacOS)? Was a bit of a pain to have to install Rust along with the 4.6 gb of C++ build tools, as I don't code these languages locally.

**Comment by darakian** [comment]
Glad you've found it useful. Ya, I can make a new release. There's a feature request pending which I'll try to get to this week and make a release with that.

**Comment by darakian** [comment]
@arimgibson 0.12.0 is up with prebuilt artifacts 
https://github.com/darakian/ddh/releases/tag/0.12.0
