### ISSUE TITLE
LGPL-3.0 is deprecated

### ISSUE THREAD

**Issue by chenrui333** [darakian/ddh#54]
[LGPL-3.0 is deprecated](https://spdx.org/licenses/LGPL-3.0.html), consider use `LGPL-3.0-only` or `LGPL-3.0-or-later`. (you can just add license header to the source file or in the README), thanks!

https://github.com/darakian/ddh/blob/e4c574ffd9855384cb35ec7534d3eba6b03ba867/Cargo.toml#L7

**Comment by darakian** [comment]
Oh interesting. I've been considering moving the license to MPL 2, but I'm curious what it means for a legal license to be deprecated. Are lawyers no longer reading up on it? 😆

**Comment by chenrui333** [comment]
>  I've been considering moving the license to MPL 2,

I'd consider that.

> but I'm curious what it means for a legal license to be deprecated. Are lawyers no longer reading up on it? 😆

There is an entity ensuring the license usage. i know we dont care. :) 

This is their repo, https://github.com/spdx/license-list-data

**Comment by darakian** [comment]
> There is an entity ensuring the license usage. 

I see. I guess it's hard to enforce if no one is actively using it.

> i know we dont care. :)

Oh, I care. There's a reason this is LGPL and not MIT after all :)
