### ISSUE TITLE
Latest release does not properly handle spaces in directory names for input arguments

### ISSUE THREAD

**Issue by fiveseven808** [darakian/ddh#7]
When using windows binary release from this commit:
https://github.com/darakian/ddh/commit/8c64d23dce401330b4c78dcf9b93a3928f78bffd

It does not handle directories with spaces in their names and crashes. 

i.e. 
ddh.exe .\ ----- Runs fine
ddh.exe ".\space in name\" ------ Causes the error below

> thread 'main' panicked at 'Error canonicalizing input: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', libcore\result.rs:945:5
> stack backtrace:
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: BaseThreadInitThunk
>   11: RtlUserThreadStart

**Comment by fiveseven808** [comment]
Exact same error message still

**Comment by darakian** [comment]
I can't reproduce this bug. Please compile from source when you can and let me know if the issue persists.

**Comment by darakian** [comment]
The latest release has a possibly temporary fix for this.

**Comment by fiveseven808** [comment]
Current release seems to be working fine now! Issue does not appear anymore.
